export const environment = {
  DEBUG_MODE: false,
  DATABASE_IP: "127.0.0.1",
  DATABASE_PORT: 3306,
  DATABASE_USERNAME: "charat",
  DATABASE_PASSWORD: "Toyota88@",
  DATABASE_DB_NAME: "gwback",
  SYNCHRONIZE: true,
  LINE_NOTIFY_TOKEN: "ZcuasZl67YahoAeTyAvQ7loyL9RU2twtbqqizkfIhp6"
    // production: false,
    // dbUrl: "127.0.0.1",
    // port: 3308,
    // dbUsername: "charat",
    // dbPassword: "Toyota8@",
    // dbName: "gwback",
    // synchronize: true,
    // sapApiToken: "",
    // jwt_secrect: "!z$C&F)J@NcRfUjXn2r5u8x/A?D*G-Ka",
    // baseUrl: "",
    // project: "Build Dev:v0.1.39 on 28/7/23",
    // release: "Back-Dev",
  };